LOCAL_INSTALL_PATH = /Library/UISettings/UICore/
include ../theos/makefiles/common.mk
TOOL_NAME = UISettingsDaemon
UIHook_FRAMEWORKS += UIKit CoreGraphics
UISettingsDaemon_FILES = main.mm

include $(THEOS_MAKE_PATH)/tool.mk
