ADDITIONAL_LDFLAGS += -framework UIKit -framework Foundation -framework CoreFoundation 
AUXILIARY_LDFLAGS += -lsubstrate
include theos/makefiles/common.mk
LOCAL_INSTALL_PATH = /Library/UISettings/UICore/
LIBRARY_NAME = UICore
UICore_FILES = UICore.mm
include $(THEOS_MAKE_PATH)/library.mk
