include theos/makefiles/common.mk
LOCAL_INSTALL_PATH = /Library/UISettings/
LIBRARY_NAME = UIToggles
UIToggles_FILES = UIToggles.xm
ADDITIONAL_LDFLAGS=-lsubstrate
UIToggles_PRIVATE_FRAMEWORKS=UIKit CoreGraphics GraphicsServices MediaPlayer
include $(THEOS_MAKE_PATH)/library.mk
